default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  port: 5432

development:
  <<: *default
  database: relocator_development

test:
  <<: *default
  database: relocator_test

production:
  <<: *default
  database: relocator_production
  username: relocator
  password: <%= ENV['RELOCATOR_DATABASE_PASSWORD'] %>
